SET IDENTITY_INSERT DIM_Borough ON;
INSERT INTO DIM_Borough
(borough_sk,Borough, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT DIM_Borough OFF;


SET IDENTITY_INSERT Dim_CONTRIBUTING_FACTOR ON;
INSERT INTO Dim_CONTRIBUTING_FACTOR
(CONTRIBUTING_FACTOR_SK,CONTRIBUTING_FACTOR, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_CONTRIBUTING_FACTOR OFF;


SET IDENTITY_INSERT Dim_DRIVER_LICENSE_JURISDICTION ON;
INSERT INTO Dim_DRIVER_LICENSE_JURISDICTION
(DRIVER_LICENSE_JURISDICTION_SK,DRIVER_LICENSE_JURISDICTION, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_DRIVER_LICENSE_JURISDICTION OFF;


SET IDENTITY_INSERT Dim_DRIVER_LICENSE_STATUS ON;
INSERT INTO Dim_DRIVER_LICENSE_STATUS
(DRIVER_LICENSE_STATUS_SK,DRIVER_LICENSE_STATUS, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_DRIVER_LICENSE_STATUS OFF;



SET IDENTITY_INSERT Dim_EMOTIONAL_STATUS ON;
INSERT INTO Dim_EMOTIONAL_STATUS
(EMOTIONAL_STATUS_SK,EMOTIONAL_STATUS, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_EMOTIONAL_STATUS OFF;


SET IDENTITY_INSERT Dim_PED_ROLE ON;
INSERT INTO Dim_PED_ROLE
(PED_ROLE_SK,PED_ROLE, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_PED_ROLE OFF;



SET IDENTITY_INSERT Dim_PERSON_INJURY ON;
INSERT INTO Dim_PERSON_INJURY
(PERSON_INJURY_SK,PERSON_INJURY, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_PERSON_INJURY OFF;
SET IDENTITY_INSERT Dim_PERSON_SEX ON;
INSERT INTO Dim_PERSON_SEX
(PERSON_SEX_SK,PERSON_SEX, DI_PID, DI_Create_Date)
VALUES(-99, 'N','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_PERSON_SEX OFF;

SET IDENTITY_INSERT Dim_PERSON_TYPE ON;
INSERT INTO Dim_PERSON_TYPE
(PERSON_TYPE_SK,PERSON_TYPE, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_PERSON_TYPE OFF;

SET IDENTITY_INSERT Dim_PUBLIC_PROPERTY_DAMAGE ON;
INSERT INTO Dim_PUBLIC_PROPERTY_DAMAGE
(PUBLIC_PROPERTY_DAMAGE_SK,PUBLIC_PROPERTY_DAMAGE, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_PUBLIC_PROPERTY_DAMAGE OFF;


SET IDENTITY_INSERT Dim_STATE_REGISTRATION ON;
INSERT INTO Dim_STATE_REGISTRATION
(STATE_REGISTRATION_SK,STATE_REGISTRATION, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_STATE_REGISTRATION OFF;


SET IDENTITY_INSERT Dim_VEHICLE_TYPE ON;
INSERT INTO Dim_VEHICLE_TYPE
(VEHICLE_TYPE_SK,VEHICLE_TYPE, DI_PID, DI_Create_Date)
VALUES(-99, 'NO VALUE PROVIDED','ManualInput', (getdate()));
SET IDENTITY_INSERT Dim_VEHICLE_TYPE OFF;



